# Generated by Django 4.0.4 on 2023-12-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booktitle', models.CharField(default='', max_length=50)),
                ('authorname', models.CharField(default='', max_length=50)),
                ('bookdescription', models.TextField(default='', max_length=500)),
                ('catagory', models.CharField(default='', max_length=50)),
                ('language', models.CharField(default='', max_length=50)),
                ('keyword', models.CharField(default='', max_length=50)),
                ('bookcover', models.FileField(upload_to='bookcovers/')),
                ('bookfile', models.FileField(upload_to='bookpdf/')),
            ],
        ),
    ]
