# Generated by Django 4.0.4 on 2023-12-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsebook', '0003_alter_bookinfo_uploadby'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='status',
            field=models.CharField(default='on', max_length=5),
        ),
    ]
